version: '2'
services:
  registry1:
    container_name: registry1
    image: apicurio/apicurio-registry-streams
    ports:
      - "8080:8080"
      - "9000"
    environment:
      QUARKUS_PROFILE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APPLICATION_ID: registry_id
      APPLICATION_SERVER: registry1:9000
  registry2:
    container_name: registry2
    image: apicurio/apicurio-registry-streams
    ports:
      - "8081:8080"
      - "9000"
    environment:
      QUARKUS_PROFILE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APPLICATION_ID: registry_id
      APPLICATION_SERVER: registry2:9000
