apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: apicurio/apicurio-registry-infinispan:latest-release
          name: registry
          env:
            - name: QUARKUS_PROFILE
              value: prod
            - name: JAVA_OPTIONS
              value: "-D%prod.registry.infinispan.transport.configurationFile=default-configs/default-jgroups-kubernetes.xml -Djgroups.dns.query=jgrp.default.svc.cluster.local"
            - name: QUARKUS_LOG_LEVEL
              value: "INFO"
          resources:
            limits:
              memory: "1000Mi"
          ports:
            - containerPort: 7800
              name: ping
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: registry
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: jgrp
  labels:
    run: jgrp
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: ping
      port: 7800
      protocol: TCP
      targetPort: 7800
  selector:
    app: registry
---